---
abstract: unknown
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0.113'
  Test::Exception: '0.32'
  Test::More: '0.31'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-IP2Location-Lite
no_index:
  directory:
    - t
    - inc
requires:
  bigint: '0'
resources:
  bugtracker: https://github.com/leejo/geo-ip2location-lite/issues
  homepage: https://metacpan.org/module/Geo::IP2Location::Lite
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/geo-ip2location-lite
version: '0.01'
